language: cpp

sudo: false

packages:
  - &boost [ 'libboost1.55-dev', 'libboost1.55-tools-dev', 'libboost-system1.55-dev', 'libboost-date-time1.55-dev', 'libboost-filesystem1.55-dev' ]

addons:
  - &gcc-5 { apt: { sources: [ 'ubuntu-toolchain-r-test', 'boost-latest' ], packages: [ *boost, 'g++-5' ] } }

matrix:
  include:
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=debug LINK=static }
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=debug LINK=shared }
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=release LINK=static }
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=release LINK=shared }

script: /bin/sh -e ./build/unix/build.sh toolset=${TOOLSET} link=${LINK} boost=system boost-link=${LINK} variant=${VARIANT}
